### ISSUE TITLE
Adding macOS recommended version for Postgres/Postgis

### ISSUE THREAD

**Issue by kamicut** [Hecate/Hecate#2]
### Context
On macOS, I could only get hecate working with Postgis 2.5+, since it is the first version to have libprotobuf support bundled in [Postgres.app](https://postgresapp.com/downloads.html) [1]. Is this something that should be in the README? 

[1] https://github.com/PostgresApp/PostgresApp/issues/412

cc/ @ingalls

**Comment by guidorice** [comment]
The [PostGIS docs](https://postgis.net/2018/09/23/postgis-2.5.0/) say PostgreSQL 11+ is recommended when using PostGIS 2.5. 

I am opening a draft PR that updates this in the Readme as well as adds semantic version parsing for the postgresql and postgis database check.
